# Generated by Django 6.0.3 on 2026-04-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
