# Generated by Django 6.0.3 on 2026-03-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='car',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='Car_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
