# Generated by Django 6.0.3 on 2026-03-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_purchase_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Car_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
