# Generated by Django 6.0.3 on 2026-04-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchase_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emihistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emihistory',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='emihistory',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
