# Generated by Django 6.0.3 on 2026-04-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emihistory_created_at_emihistory_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emihistory',
            name='paid_emi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emihistory',
            name='total_emi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
