# Generated by Django 6.0.3 on 2026-03-16 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_purchase_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Car_name',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='car_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
