# Generated by Django 6.0.3 on 2026-04-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emihistory_paid_emi_emihistory_total_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
