# Generated by Django 6.0.3 on 2026-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_purchase_car_name_alter_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='car_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
