# Generated by Django 6.0.3 on 2026-03-16 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_purchase_amount_alter_purchase_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='car_name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.car'),
        ),
    ]
