# Generated by Django 6.0.3 on 2026-04-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tranmission',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
