# Generated by Django 6.0.3 on 2026-04-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_car_tranmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='number',
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
