# Generated by Django 6.0.3 on 2026-03-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_purchase_car_name_purchase_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
