# Generated by Django 6.0.3 on 2026-04-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_car_number_car_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='tranmission',
            new_name='transmission',
        ),
    ]
