# Generated by Django 6.0.3 on 2026-04-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_tranmission_car_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_name',
            new_name='model',
        ),
    ]
