# Generated by Django 6.0.3 on 2026-04-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_car_fuel_type_alter_car_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
