# Generated by Django 6.0.3 on 2026-04-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
