# Generated by Django 6.0.3 on 2026-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='insurance_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_insurance',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
