# Generated by Django 6.0.3 on 2026-04-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_testdrive_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
