# Generated by Django 6.0.3 on 2026-03-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_emihistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='emihistory',
            name='car_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
