# Generated by Django 6.0.3 on 2026-03-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
